# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'Todos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todos
  pod 'RealmSwift'

end
